/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "dev.thource.wurmunlimited.clientmods"
version = "1.0.0"
description = "Thource's Minimap Mod"
java.sourceCompatibility = JavaVersion.VERSION_1_8

dependencies {
    implementation(files("F:\\SteamLibrary\\steamapps\\common\\Wurm Unlimited\\WurmLauncher\\client-patched.jar"))
    implementation(files("F:\\SteamLibrary\\steamapps\\common\\Wurm Unlimited\\WurmLauncher\\common.jar"))
    implementation(files("F:\\SteamLibrary\\steamapps\\common\\Wurm Unlimited\\WurmLauncher\\javassist.jar"))
    implementation(files("F:\\SteamLibrary\\steamapps\\common\\Wurm Unlimited\\WurmLauncher\\modlauncher.jar"))
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
